### ISSUE TITLE
Could I ask a question about h5py ？The following is my mistake ，thanks

### ISSUE THREAD

**Issue by wangWilson** [qobilidop/srcnn#12]
19328/19382 [============================>.] - ETA: 0s - loss: 2099.9664 - psnr: 20.0429Traceback (most recent call last):
  File "run.py", line 37, in <module>
    epochs=param['epochs'], resume=True)
  File "D:\wyj\srcnn-master\toolbox\experiment.py", line 125, in train
    validation_data=(x_val, y_val), initial_epoch=initial_epoch)
  File "C:\Users\dellc4130\Anaconda3\envs\tensorflow\lib\site-packages\keras\models.py", line 960, in fit
    validation_steps=validation_steps)
  File "C:\Users\dellc4130\Anaconda3\envs\tensorflow\lib\site-packages\keras\engine\training.py", line 1657, in fit
    validation_steps=validation_steps)
  File "C:\Users\dellc4130\Anaconda3\envs\tensorflow\lib\site-packages\keras\engine\training.py", line 1233, in _fit_loop
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "C:\Users\dellc4130\Anaconda3\envs\tensorflow\lib\site-packages\keras\callbacks.py", line 73, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "C:\Users\dellc4130\Anaconda3\envs\tensorflow\lib\site-packages\keras\callbacks.py", line 426, in on_epoch_end
    self.model.save(filepath, overwrite=True)
  File "C:\Users\dellc4130\Anaconda3\envs\tensorflow\lib\site-packages\keras\engine\topology.py", line 2556, in save
    save_model(self, filepath, overwrite, include_optimizer)
  File "C:\Users\dellc4130\Anaconda3\envs\tensorflow\lib\site-packages\keras\models.py", line 57, in save_model
    raise ImportError('`save_model` requires h5py.')
ImportError: `save_model` requires h5py.
Exception ignored in: <bound method BaseSession.__del__ of <tensorflow.python.client.session.Session object at 0x000001C80ED4AC88>>
Traceback (most recent call last):
  File "C:\Users\dellc4130\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 696, in __del__
TypeError: 'NoneType' object is not callable

**Comment by qobilidop** [comment]
@wangWilson Looks like h5py is not installed. Could you try installing h5py in your conda environment?
